[package]
name = "nativeWindowsGUI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-windows-derive = "1.0.4"
native-windows-gui = "1.0.12"
winapi = "0.3.9"